<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ecoSansar - Reusable Item Enquiry</title>

    <style>
        body {
            margin: 0;
            padding: 0;
            background: #edf2f7;
            font-family: Arial, Helvetica, sans-serif;
            color: #333;
        }

        .container {
            width: 100%;
            padding: 40px 0;
        }

        .email-box {
            width: 700px;
            margin: auto;
            background: #ffffff;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 8px rgba(0,0,0,.08);
        }

        .header {
            background: #3a7d44;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        .header h2 {
            margin: 0;
            font-size: 26px;
        }

        .content {
            padding: 30px;
        }

        .content p {
            margin-top: 0;
            font-size: 15px;
            line-height: 24px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table th {
            background: #f5f5f5;
            text-align: left;
            padding: 12px;
            width: 35%;
            border: 1px solid #ddd;
        }

        table td {
            padding: 12px;
            border: 1px solid #ddd;
        }

        .footer {
            background: #f5f5f5;
            text-align: center;
            padding: 20px;
            font-size: 13px;
            color: #666;
        }

        .footer strong {
            color: #3a7d44;
        }
    </style>
</head>

<body>

<div class="container">

    <div class="email-box">

        <!-- Header -->
        <div class="header">
            <h2>ecoSansar</h2>
            <p style="margin:8px 0 0;">New Reusable Item Enquiry</p>
        </div>

        <!-- Body -->
        <div class="content">

            <p>Hello Admin,</p>

            <p>
                A new enquiry has been submitted through the
                <strong>Reusable Item Listing</strong> on the ecoSansar website.
                The enquiry details are provided below.
            </p>

            <table>
                <tr>
                    <th>Name</th>
                    <td>{{ $enquiry->name }}</td>
                </tr>

                <tr>
                    <th>Contact Number</th>
                    <td>{{ $enquiry->mobile }}</td>
                </tr>

                <tr>
                    <th>Quantity</th>
                    <td>{{ $enquiry->quantity }}</td>
                </tr>

                <tr>
                    <th>Colour of Lid</th>
                    <td>{{ $enquiry->lid_colour ?: '-' }}</td>
                </tr>

                <tr>
                    <th>Place of Delivery</th>
                    <td>{{ $enquiry->delivery_place }}</td>
                </tr>

                <tr>
                    <th>Required By Date</th>
                    <td>{{ $enquiry->required_by_date }}</td>
                </tr>

                <tr>
                    <th>Additional Notes</th>
                    <td>{{ $enquiry->notes ?: '-' }}</td>
                </tr>

                <tr>
                    <th>Submitted On</th>
                    <td>{{ $enquiry->created_at->format('d M Y h:i A') }}</td>
                </tr>
            </table>

            <p style="margin-top:30px;">
                Please review the enquiry and contact the customer at the earliest convenience.
            </p>

            <p>
                Regards,<br>
                <strong>ecoSansar System</strong>
            </p>

        </div>

        <!-- Footer -->
        <div class="footer">
            <strong>ecoSansar</strong><br>
            This is an automated notification generated by the ecoSansar website.<br>
            <!--Please do not reply directly to this email.-->
        </div>

    </div>

</div>

</body>
</html>